---
title: "Chapter 7 Notes and Exercises"
output:
  html_document:
    df_print: paged
---

## Vocabulary
```{r}
# A **variable** is a quantity, quality, or property that you can measure.

# A **value** is the state of a variable when you measure it. The value of a variable may change from measurement to measurement.

# An **observation** is a set of measurements made under similar conditions (you usually make all of the measurements in an observation at the same time and on the same object). An observation will contain several values, each associated with a different variable. I’ll sometimes refer to an observation as a data point.

# **Tabular** data is a set of values, each associated with a variable and an observation. Tabular data is tidy if each value is placed in its own “cell”, each variable in its own column, and each observation in its own row.

# **Variation** is the tendency of the values of a variable to change from measurement to measurement.

# A variable is **categorical** if it can only take one of a small set of values.
  # use a bar chart

# A variable is **continuous** if it can take any of an infinite set of ordered values. Numbers and date-times are two examples of continuous variables.
  # You can compute this by hand by combining dplyr::count() and ggplot2::cut_width():

# **Covariation** is the tendency for the values of two or more variables to vary together in a related way.

# A **boxplot** is a type of visual shorthand for a distribution of values that is popular among statisticians. Each boxplot consists of:
   #A box that stretches from the 25th percentile of the distribution to the 75th percentile, a distance known as the interquartile range (IQR). In the middle of the box is a line that displays the median, i.e. 50th percentile, of the distribution.
   #Outliers that display observations that fall more than 1.5 times the IQR from either edge of the box.
    #A line (or whisker) that extends from each end of the box and goes to the farthest non-outlier point in the distribution.

```

### 7.3.4 Exercises
```{r}
# 1) X and Y are virtually similar, but the length is poportional to the Y value directly.
# 2) Distribution decreases (?)
# 3) 0.99 - 23
# 4) 
```

### 7.4.1 Exercises
```{r}
# 1) NA disappears in the barplot.
# 2) Removes the NA function.
```

### 7.5.1.1 Exercises
```{r}
# 1) Use a boxplot instead of a frequency plot.
# 2)  The price ant carat are correlated -- the higher the carat the higher the price.
# 3) 
# 4) Histograms can be deceptive. 
```

### 7.5.2.1 Exercises
```{r}
# 1) Calculate the percentage of n.
# 2) There are missing values that make the chart incorrect, and thus the higher values are controlling the scale.
# 3) Longer names are better placed on the y-axis.
```
### 7.5.3.1 Exercises
```{r}
# 1) Use a boxplot instead of a frequency plot.
# 2)  
ggplot(diamonds, aes(carat, y = ..density.., colour = cut_width(price, 2000))) +
  geom_freqpoly()

# 3) Larger diamonds have a large variance in price (5k to 18k). Small diamonds have very little variance.
# 4) 
# 5) Scatterplots tend to visualize linear relationships best.
```